# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "hqol"
mod.name = "HypixelQol"
mod.group = "de.steingaming"
mod.version = "v3.6.0"

deps.fabric_loader = "0.19.3"
loomx.loom_version = "1.17-SNAPSHOT"


["1.21.11"]
mod.mc_compat = "1.21.11"
mod.mc_releases = ["1.21.11"]

deps.fabric_api = "0.141.3+1.21.11"

moulconfig.version = "4.6.0"
modmenu_version = "17.0.0"

["26.1"]
mod.mc_compat = "~26.1"
mod.mc_releases = ["26.1", "26.1.1"]

deps.fabric_api = "0.145.3+26.1.1"

modmenu_version = "18.0.0"
moulconfig.version = "4.6.0"


["26.2"]
mod.mc_compat = "~26.2"
mod.mc_releases = ["26.2"]

deps.fabric_api = "0.152.2+26.2"

moulconfig.version = "4.7.2"
modmenu_version = "20.0.1"
