# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: |
          21
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Build
      run: ./gradlew buildAndCollect
    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        file_glob: true
        file: build/output/*.jar
